default_language_version:
  python: python3.14
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: double-quote-string-fixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.22
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.16.5
    hooks:
      - id: commitizen
        stages: [commit-msg]
